0.2.23

diff --git a/lib/bin/sparky-center-exe b/lib/bin/sparky-center-exe
--- a/lib/bin/sparky-center-exe
+++ b/lib/bin/sparky-center-exe
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# Last update 2018/03/29
+
 testroot="`whoami`"
 if [ "$testroot" != "root" ]
 then
@@ -7,10 +9,11 @@ then
 	exit 1
 fi
 
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="sparky-terminal -e"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
 else
-	SPARKYXTERM="x-terminal-emulator -e"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 if [ "$1" = "editor" ]; then
@@ -38,7 +41,7 @@ elif [ "$1" = "pcmanfm" ]; then
 	pcmanfm
 
 elif [ "$1" = "sparky-terminal" ]; then
-	sparky-terminal
+	x-terminal-emulator
 
 fi
 
diff --git a/lib/bin/sparky-mixer b/lib/bin/sparky-mixer
--- a/lib/bin/sparky-mixer
+++ b/lib/bin/sparky-mixer
@@ -3,8 +3,8 @@
 # This script choose and run a sound mixer depends 
 # which one is installed
 # Created by Paweł "pavroo' Pijanowski 2015/03/19
-# Copyright 2015, 2016 under the GNU GPL2 License
-# Last update 2016/06/11
+# Copyright 2015-2018 under the GNU GPL2 License
+# Last update 2018/03/29
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus"
@@ -33,13 +33,19 @@ TITLE="--always-print-result --dialog-sep --image=multimedia-volume-control --ti
 TITLETEXT="$LOCAL19"
 MSGBOX=" --button=Ok:0 "
 TEXT="--text="
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
+else
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
+fi
 
 if [ -f /usr/bin/pavucontrol ]; then
 	/usr/bin/pavucontrol
 elif [ -f /usr/bin/gnome-alsamixer ]; then
 	/usr/bin/gnome-alsamixer
 elif [ -f /usr/bin/alsamixer ]; then
-	/usr/bin/sparky-terminal -e /usr/bin/alsamixer
+	$SPARKYXTERM /usr/bin/alsamixer
 else
 	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL20"
 	exit 0
